### ISSUE TITLE
Identifier not found or not unique

### ISSUE THREAD

**Issue by Redstrawberry7** [RossJH/Solidity#4]
I am importing local files by entering "./Context.sol" but am getting an error Identifier not found or not unique. Is there another way to import files so that it can read their code

**Comment by RossJH** [comment]
What IDE are you using and is this in py? If you are using VScode you may need NPM installed and or the solidity extensions for .sol files.

**Comment by Redstrawberry7** [comment]
I have the solidity and remix extensions installed

**Comment by RossJH** [comment]
If you are trying to import a file into a contract it should be: 

import "./SushiToken.sol";

**Comment by Redstrawberry7** [comment]
Thanks yes that is what I am doing is there any other thing that could be wrong or another way to import it


On 13 Mar 2022, at 10:19 am, Ross Hardingham ***@***.***> wrote:

﻿

If you are trying to import a file into a contract it should be:

import "./SushiToken.sol";

—
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FRossJH%2FSolidity%2Fissues%2F4%23issuecomment-1065990722&data=04%7C01%7C%7Cc9b34fc10f7245a5eb9108da04872c24%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637827275861248764%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=%2FwDqQcoT9ZYxrdXj6nuoWQnN0L7JhKMY0HpGKCNyUPM%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAXDHS7DWQ2RRMW6BEEWQQCLU7UYB5ANCNFSM5QSRAKAA&data=04%7C01%7C%7Cc9b34fc10f7245a5eb9108da04872c24%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637827275861248764%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=7bnGAXpNDV1OMmdmUdAaZsP6C3ligfCF97DCDgoUjz4%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7Cc9b34fc10f7245a5eb9108da04872c24%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637827275861248764%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=OvTzIgX0K3Qd1t4qc1lXY2fUL%2BoX2S94yld%2Bg%2FNOk94%3D&reserved=0> or Android<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7Cc9b34fc10f7245a5eb9108da04872c24%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637827275861248764%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=cHgfcKkYx%2BaSuwDnQk9aafIUOcRjG5gzN47uKgfzN1U%3D&reserved=0>.

**Comment by RossJH** [comment]
Double-check your file paths are correct,  I'm not sure what else is blocking it but if you figure it out let me know.

**Comment by Redstrawberry7** [comment]
Like this

Would it be an idea to add all the files into one file. Or would it cause the file to be too large.

**Comment by RossJH** [comment]
I didn't see any attachment? 

So a file can have multiple contracts and when you are importing it is adding another file's contract into your main file usually a Masterchef. 

It isn't always best practice to add everything to one file for production smart contracts. There are multiple reasons for this one being to optimize/save gas you can make a library and just import it multiple times into different files/contracts. 

An example is Openzeppelin SafeMath: import "@openzeppelin/contracts/math/SafeMath.sol"; 

Hope that helps best of luck with it.
